### ISSUE TITLE
Upgrade to robovm 1.3.0

### ISSUE THREAD

**Issue by pavlosgi** [roboscala/sbt-robovm#33]

**Comment by Darkyenus** [comment]
Check [my fork](https://github.com/Darkyenus/sbt-robovm), in meantime, it is usually kept updated.

**Comment by pavlosgi** [comment]
Thanks, I am trying to use it but it seems quite different. Can you provide an example

**Comment by Darkyenus** [comment]
There are samples forked and updated to my version [here](https://github.com/Darkyenus/roboscala-samples).

**Comment by pavlosgi** [comment]
Thank you that's great. Any plans for porting HTML as well?

**Comment by Darkyenus** [comment]
Link in __Setup__ section of https://github.com/Darkyenus/sbt-robovm readme already points to https://github.com/Darkyenus/roboscala-samples. Did I miss something or misunderstood? The readme is not entirely clear on the setup process yet, because it was written when it still looked like a fork that would get eventually merged or replaced when the original plugin gets updated. However it looks like that is not going to happen soon, so I'll probably put some work into clearing it up and promoting it a bit (which I didn't want to do before to not divert people away from here).

**Comment by ajhager** [comment]
This should be fixed by 7c4ea6a085062fd04e89689a86763ae4f4cf3c71. Please open a new issue if you are still having issues after the release.
